version: "3.8"

services:
  app:
    image: node:20-alpine
    container_name: test-app2
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    working_dir: /app
    command: ["npm", "start"]
